### ISSUE TITLE
E10 als Vergleichskraftstoff hinzufügen

### ISSUE THREAD

**Issue by JKBusse** [RundesBalli/tankersparnis#3]
Moin!
Wäre es vielleicht möglich, die Ersparnisse zwischen E10 und E5 mit ein zu pflegen? 
Mich würde Interessieren, ob man mit E10 Geld sparen kann. 

Danke im Vorraum.

p.s. Habe dich bei Sascha entdeckt.

**Comment by RundesBalli** [comment]
Hi,

ich hatte dies bereits geplant, allerdings wieder verworfen, da es keine belastbaren Quellen für den Heizwert von E10 gibt.

Tankersparnis rechnet das Verhältnis "Gas / Benzin" oder "Gas / Diesel" anhand des Heizwertes der Kraftstoffe aus.

Sofern es eine belastbare Quelle für den Heizwert von E10 gibt, werde ich dies sofort einfügen.

Gruß

**Comment by JKBusse** [comment]
Moin,
Ich habe mal ein wenig in den Normen gesucht (u.a. EN228) und habe ein wenig gerechnet. Ich komme auf 11183wh/kg Heizwert für E10.
Ob das jetzt eine belastbare Quelle ist? Keine Ahnung. 

Grüße.

**Comment by RundesBalli** [comment]
Bin mir da nicht ganz sicher, ob das so richtig ist. Wenn ich das richtig im Kopf habe, ist E10 weniger Leistungsstark als E5.

Aktuell sind folgende Werte bei Tankersparnis hinterlegt:
https://github.com/RundesBalli/tankersparnis/blob/fe45545ea3432a31bef892ec9e43707a453c086b/sql/tankersparnis.sql#L103-L104

**Comment by JKBusse** [comment]
Wenn ich meinen Wert in kWh/L umrechne komme ich auf 8,387 kWh/L. Das dürfte schon passen.

**Comment by RundesBalli** [comment]
Pro Liter, genau.

Kannst du deinen Rechenweg einmal belegen, bitte? Dann trage ich das gleich sofort ein.

**Comment by JKBusse** [comment]
Hier (https://www.88energie.de/kein-nennenswerter-mehrverbrauch-durch-e10-zweifel-an-testergebnissen-von-auto-bild-352543.html) heißt es das der Energie Gehalt von E10 maximal 1,9% geringer sein kann als von E5. Das habe ich anhand von anderen Quellen auch verifizieren können. Laut DIN hat E5 in DE 11,4 kWh/kg. 11400 - 1,9% = 11183. Jetzt das Ganze noch in Liter Umrechnen und man kommt auf 8,387 kWh/L E10.

**Comment by RundesBalli** [comment]
Ich habe mich auch nochmal etwas eingelesen und komme auf 8,376kWh/L, Ich werde 8,38 nehmen, das wird passen. Ganz genau passt es eh nie, da jeder Kraftstoff andere Qualität hat, deshalb soll das als Mittelwert wohl ausreichen.

**Comment by JKBusse** [comment]
Ich denke auch, das dürfte passen. Rein aus Interesse, welche Dichte hast du angenommen um in kWh/L umzurechnen? Ich habe mit 0,75 gerechnet. Benzin hat wohl eine Dichte zwischen 0,72 und 0,78.

**Comment by JKBusse** [comment]
Jo, dann dürfte das Passen. Dann würde ich den Issiue schließen, wenn du nichts dagegen hast?

**Comment by RundesBalli** [comment]
Erledigt. Danke für deinen Beitrag!

**Comment by JKBusse** [comment]
Dank dir für die schnelle Hilfe!

**Comment by RundesBalli** [comment]
Gerne!

**Comment by RundesBalli** [comment]
Achso, ja da haben wir uns tatsächlich falsch verstanden. Die Lösung jetzt find ich aber auch gut :-D

Ganz verstanden hab ich das dann doch noch nicht, was du vor hast. Du möchtest also, dass da wo LPG, CNG, usw. steht, auch E10 und E5 steht?

**Comment by RundesBalli** [comment]
Wir machen mal ein Rechenbeispiel:
Jetzt gerade ist lt. [Tankerkönig.de API](https://creativecommons.tankerkoenig.de/api/v4/stats) (ApiKey kann ich jetzt natürlich nicht bereitstellen), der Medianpreis folgendes:
E5: 1,779€/l
E10: 1,729€/l

Nehmen wir jetzt die Formel von hier:
https://github.com/RundesBalli/tankersparnis/blob/master/public/inc/addEntry.php#L134-L140
dann rechnen wir folgendes:

Verbrauch: 8,5 Liter / 100km, deshalb:
Getankt: 34 Liter E10, Energie: 34 × 8,38 = 284,92kW
Kosten E10: 1,729 × 34 = 58,786 = **58,79 €**
Benötigte Menge E5: 284,92 ÷ 8,6 (E5 Heizwert, siehe oben) = 33,130232558 = 33,13 Liter
Kosten E5: 1,779 × 33,13 = 58,93827 = **58,94 €**
Ersparnis E10 gegenüber E5: ((58,79 ÷ 58,94 = 0,997455039) - 1 = -0,002544961) × 100 = -0,254496098 = **0,2545 % Ersparnis**

Ich unterstelle jetzt mal einfach ganz frech, dass diesen Vergleich kaum jemanden interessieren wird.
Und wie die Seite auf der Startseite schon sagt:
https://github.com/RundesBalli/tankersparnis/blob/master/public/inc/start.php#L24
"Gas" gegenüber "herkömmlichem Kraftstoff". Dabei würde ich es gerne belassen, da der Vergleich E5/E10 im ganzen Jahr wenige Euro darstellen wird und vermutlich innerhalb der "KFZ Anlegen" Funktion nur Verwirrung stiften wird.

Danke dennoch für deinen Vorschlag.
