### ISSUE TITLE
Import aus "Car Report" Android App

### ISSUE THREAD

**Issue by dursch** [RundesBalli/tankersparnis#5]
Ein Import aus der App "Car Report" wäre sehr cool!

Export mit 2 Fahrzeugen:
[cr-2022-07-11.zip](https://github.com/RundesBalli/tankersparnis/files/9083346/cr-2022-07-11.zip)

F-Droid: https://f-droid.org/de/packages/me.kuehle.carreport/

**Comment by RundesBalli** [comment]
Hallo,

ist es vielleicht möglich, dass du die Daten als CSV exportierst?

![grafik](https://user-images.githubusercontent.com/46271553/179320820-7a891073-1481-415f-a5ab-98b4e3f93c54.png)

Optimalerweise noch für jedes Fahrzeug separat.
Dann schaue ich mir das gerne mal an.

Gruß

**Comment by RundesBalli** [comment]
> ist es vielleicht möglich, dass du die Daten als CSV exportierst?

Scheinbar nicht.
