### ISSUE TITLE
LPG + Benzin tanken

### ISSUE THREAD

**Issue by AndyK70** [RundesBalli/tankersparnis#7]
Wäre es möglich die Menge an getanktem Benzin ebefalls zu erfassen?

Mein Auto hat eine Direkteinspritzung und meine Prins LPG Anlage/Steuergerät macht eine automatische Beimischung von 3% Benzin zum LPG.
Dazu kommt auch, dass das Prins Steuergerät erst ab einer Verdampfertemperatur von 35°C auf Gasbetrieb umschaltet. Bei den Temperaturen jetzt im Sommer ist das nicht einmal ein Kilometer, im Winter kann das aber schon ein wenig dauern, bis der Verdampfer durch den inneren Kühlkreislauf soweit erwärmt wurde, dass auf Gasbetrieb umgeschaltet wird.
Ich muss also immer auch etwas Benzin tanken und würde mich freuen, wenn ich auch die getanke Benzinmenge erfassen könnte.
Wenn das auch noch in die Ersparnisberechnung mit einfließen könnte, wäre es natürlich klasse.

**Comment by RundesBalli** [comment]
Ich habe mich beim Entwickeln der Seite absichtlich gegen so eine Benzinverbrauchserfassung entschieden, da ich in meinem Fall zwischen 10 und 15tkm mit einer Benzinfüllung hinkomme und das so unwesentlich ins Gewicht fällt, dass es den Aufwand nicht gelohnt hätte.

Da das ganze eh nur auf ungefähren Werten basiert und von Auto zu Auto, von Gasanlage zu Gasanlage, und von Kraftstoff zu Kraftstoff z.T. stark variiert, kann man es sowieso nicht so präzise machen, dass es immer zu 100% passt. Ich denke, wenn man jetzt noch eine Benzinbeimischung mit einkalkulieren würde, wird das nur unnötig kompliziert und hat dann nur noch mehr Funktionen auf der Seite, die verwirren könnten. Wenn ich manchmal sehe was für Nachfragen per Mail kommen, wird so eine Beimischungsfunktion nur noch mehr verwirren.

Ich würde vorerst von solch einer Funktion absehen.
